on:
    push:
      branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Install goose
        run: |
          go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Set up Go
        run: ./scripts/buildprod.sh

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use Google Artifact Registry
        run: gcloud auth configure-docker REGION-docker.pkg.dev

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="us-central1-docker.pkg.dev/notely-440709/notely-ar-repo/notely"
          gcloud builds submit --tag ${IMAGE_NAME}:latest .
    
      - name: Migrate DB
        run: ./scripts/migrateup.sh

      - name: Deploy to Cloud Run
        run: gcloud run deploy notely --image us-central1-docker.pkg.dev/notely-440709/notely-ar-repo/notely:latest --region us-central1 --allow-unauthenticated --project notely-440709 --max-instances=4
          